In [26]:
import numpy as np
import pandas as pd
import torch
import torch.nn as nn
import matplotlib.pyplot as plt
from torch.utils.data import Dataset, DataLoader, ConcatDataset, random_split
import torchvision.transforms as transforms
import torchvision.models as models
from torch import optim
import json
import torch.optim.lr_scheduler as lr_scheduler
import os

from tqdm import tqdm
from utils import util_functions, metric_functions, custom_dataset

In [27]:
train_labels_path = os.path.join('dataset', 'train.csv')
test_labels_path = os.path.join('dataset', 'test.csv')

train_images_dir = os.path.join('dataset', 'train')
test_images_dir = os.path.join('dataset', 'test')

train_labels_df = pd.read_csv(train_labels_path)
test_labels_df = pd.read_csv(test_labels_path)

In [ ]:
models.cmal

In [44]:
img_size = 400
with_path = False
# Calculate the mean and std of dataset
base_transformer =  transforms.Compose([transforms.Resize((img_size, img_size)),
                                transforms.ToTensor()])
base_dataset = custom_dataset.CustomDataset(images_dir=train_images_dir, 
                                                df=train_labels_df, transforms=base_transformer)

mean, std = util_functions.calculate_mean_std_of_dataset(base_dataset)
print(mean)
print(std)

# Calculate the mean and std of dataset
base_transformer =  transforms.Compose([transforms.Resize((img_size, img_size)),
                                transforms.ToTensor()])

base_dataset = custom_dataset.CustomDataset(images_dir=train_images_dir, 
                                                df=train_labels_df, transforms=base_transformer, is_test=False, with_path=with_path)

mean, std = util_functions.calculate_mean_std_of_dataset(base_dataset, with_path=with_path)



train_transformer = transforms.Compose([transforms.Resize((img_size, img_size)),
                                transforms.RandomHorizontalFlip(),
                                transforms.RandomRotation(180),
                                # transforms.ColorJitter(brightness=0.2, contrast=0.2, saturation=0, hue=0),
                                transforms.ColorJitter(brightness=0.2, contrast=0.2),
                                # transforms.RandomApply([transforms.GaussianBlur(kernel_size=3)], p=0.2),
                                transforms.ToTensor(),
                                transforms.Normalize(mean, std)])

base_test_dataset = custom_dataset.CustomDataset(images_dir=test_images_dir, 
                                                df=train_labels_df, transforms=base_transformer, is_test=True)

# test_mean, test_std = util_functions.calculate_mean_std_of_dataset(base_test_dataset, is_test=True)
test_transformer = transforms.Compose([transforms.Resize((img_size, img_size)),
                                transforms.ToTensor(),
                                transforms.Normalize(mean, std)])

import copy

train_size = int(0.8 * len(base_dataset))
val_size = len(base_dataset) - train_size
base_train_dataset, val_dataset = random_split(base_dataset, [train_size, val_size])
base_train_dataset = copy.deepcopy(base_train_dataset)
augment_dataset = copy.deepcopy(base_train_dataset)
augment_dataset.dataset.transforms = train_transformer
val_dataset.dataset.transforms = test_transformer
train_dataset = ConcatDataset([base_train_dataset, augment_dataset])
test_dataset = custom_dataset.CustomDataset(images_dir=test_images_dir, 
                                                df=train_labels_df, transforms=test_transformer, is_test=True)

## Checking how many different classes we have
no_classes = len(list(train_labels_df['label'].unique()))

print(len(train_dataset), len(val_dataset), len(test_dataset))
BATCH_SIZE = 64 # efficientnetv2-m got cuda out of memory with 128
# train_loader = DataLoader(train_dataset, batch_size=BATCH_SIZE, shuffle=False)
train_loader = DataLoader(augment_dataset, batch_size=BATCH_SIZE, shuffle=True)
val_loader = DataLoader(val_dataset, batch_size=BATCH_SIZE, shuffle=False)
test_loader = DataLoader(test_dataset, batch_size=BATCH_SIZE, shuffle=False)

tensor([0.4741, 0.4623, 0.4588])
tensor([0.2617, 0.2613, 0.2666])
6616 827 4080

In [120]:
# model_path = f'results/2023-11-30_22-17/best_model.pt'
model_path = f'results/2023-12-01_18-01/best_model.pt'
# model = models.efficientnet_v2_s(pretrained=True)
# model.classifier[1].out_features = no_classes
# model = models.mobilenet_v2(pretrained=True)
# model.classifier[-1].out_features = no_classes

model = models.efficientnet_v2_s(pretrained=True)
model.classifier[-1].out_features = no_classes

# model = models.resnet152(pretrained=True)
# model = models.resnet34(pretrained=True)
# model.fc = nn.Linear(model.fc.in_features, no_classes)
import torchvision
# model = torchvision.models.efficientnet_v2_s(weights=torchvision.models.EfficientNet_V2_S_Weights.IMAGENET1K_V1)
# model.classifier[-1].out_features = no_classes
model.load_state_dict(torch.load(model_path, map_location='cpu'))
# resutls = metric_functions.perform_inference(model, save_results_path, test_labels_path, test_loader)

/home/student/sinaziaee/mini_conda/miniconda3/envs/test/lib/python3.11/site-packages/torchvision/models/_utils.py:208: UserWarning: The parameter 'pretrained' is deprecated since 0.13 and may be removed in the future, please use 'weights' instead.
  warnings.warn(
/home/student/sinaziaee/mini_conda/miniconda3/envs/test/lib/python3.11/site-packages/torchvision/models/_utils.py:223: UserWarning: Arguments other than a weight enum or `None` for 'weights' are deprecated since 0.13 and may be removed in the future. The current behavior is equivalent to passing `weights=EfficientNet_V2_S_Weights.IMAGENET1K_V1`. You can also use `weights=EfficientNet_V2_S_Weights.DEFAULT` to get the most up-to-date weights.
  warnings.warn(msg)

In [121]:
from PIL import Image
predicted_labels = []
model.eval()
with torch.no_grad():
    for path in list(test_labels_df['id'].values):
        with open(f'dataset/{path}', 'rb') as f:
            img = Image.open(f).convert('RGB')
            img = test_transformer(img)
            img = img.unsqueeze(0)
            output = model(img)
            _, pred = torch.max(output.data, 1)
            predicted_labels.append(pred.item())
test_labels_df['Predicted'] = predicted_labels

In [122]:
save_results_path = 'dataset/final7.csv'
test_labels_df.to_csv(save_results_path, index=False)

/home/student/sinaziaee/mini_conda/miniconda3/envs/test/lib/python3.11/site-packages/torchvision/models/_utils.py:208: UserWarning: The parameter 'pretrained' is deprecated since 0.13 and may be removed in the future, please use 'weights' instead.
  warnings.warn(
/home/student/sinaziaee/mini_conda/miniconda3/envs/test/lib/python3.11/site-packages/torchvision/models/_utils.py:223: UserWarning: Arguments other than a weight enum or `None` for 'weights' are deprecated since 0.13 and may be removed in the future. The current behavior is equivalent to passing `weights=EfficientNet_V2_S_Weights.IMAGENET1K_V1`. You can also use `weights=EfficientNet_V2_S_Weights.DEFAULT` to get the most up-to-date weights.
  warnings.warn(msg)

In [96]:
temp_dic = {}
for each in range(100):
    sample = list(train_labels_df[train_labels_df['label'] == each]['id'].values)
    temp_dic[int(each)] = sample
with open('dic.json', 'w') as json_file:
    json.dump(temp_dic, json_file)
    
with open('dic.json', 'r') as json_file:
    temp_dic = json.load(json_file)

In [115]:
df1 = pd.read_csv('dataset/final2.csv')
df2 = pd.read_csv('dataset/final3.csv')
df3 = pd.read_csv('dataset/final4.csv')
df4 = pd.read_csv('dataset/final5.csv')
df5 = pd.read_csv('dataset/final6.csv')
df6 = pd.read_csv('dataset/final7.csv')
all_dfs = df1
for temp_df in [df2, df3, df4, df5, df6]:
    all_dfs = pd.concat([all_dfs, temp_df['Predicted']], axis=1)

In [116]:
all_dfs.head(20)

,id,Predicted,Predicted,Predicted,Predicted,Predicted,Predicted
0,test/4136.jpg,90,92,92,92,91,91
1,test/4137.jpg,67,67,67,67,67,67
2,test/4138.jpg,21,21,21,21,21,21
3,test/4139.jpg,49,49,49,49,49,49
4,test/4140.jpg,38,38,38,38,38,38
5,test/4141.jpg,97,97,97,97,97,97
6,test/4142.jpg,72,72,72,72,72,72
7,test/4143.jpg,40,40,40,40,40,40
8,test/4144.jpg,22,17,22,22,22,22
9,test/4145.jpg,11,11,8,11,8,8
10,test/4146.jpg,21,21,21,21,21,21
11,test/4147.jpg,70,70,70,70,70,70
12,test/4148.jpg,96,96,96,96,11,48
13,test/4149.jpg,80,80,80,80,80,80
14,test/4150.jpg,33,33,33,33,32,33
15,test/4151.jpg,52,22,21,52,21,26
16,test/4152.jpg,20,20,20,20,20,20
17,test/4153.jpg,58,58,59,58,58,58
18,test/4154.jpg,19,19,19,19,19,19
19,test/4155.jpg,95,95,95,95,95,95

In [117]:
import copy

majority_col1 = all_dfs.mode(axis=1, numeric_only=True).iloc[:, 0]
majority_col1 = [int(each) for each in majority_col1.values]
id_list = list(all_dfs['id'])
final_df = pd.DataFrame({'id':id_list, 'Predicted':majority_col1})

In [118]:
final_df.head(20)

               id  Predicted
0   test/4136.jpg         92
1   test/4137.jpg         67
2   test/4138.jpg         21
3   test/4139.jpg         49
4   test/4140.jpg         38
5   test/4141.jpg         97
6   test/4142.jpg         72
7   test/4143.jpg         40
8   test/4144.jpg         22
9   test/4145.jpg          8
10  test/4146.jpg         21
11  test/4147.jpg         70
12  test/4148.jpg         96
13  test/4149.jpg         80
14  test/4150.jpg         33
15  test/4151.jpg         21
16  test/4152.jpg         20
17  test/4153.jpg         58
18  test/4154.jpg         19
19  test/4155.jpg         95

In [119]:
save_results_path = 'dataset/final10.csv'
final_df.to_csv(save_results_path, index=False)